info:
  contact: {}
paths:
  /admin/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Get Users
      tags:
      - Get Users
swagger: "2.0"
